### ISSUE TITLE
BTN ou Relay ON = commute

### ISSUE THREAD

**Issue by fdp1nm** [amg0/plugin-jeeipxv3#7]
Lorsqu'on clic sur le bouton ON d'un relais alors que celui-ci est déjà à l'état 1, il passe à l'état 0. La commande exécutée est donc une commande "Commute" et non une commande ON, ce qui pose problème si on envoie des commandes ON sans vérifier avant l'état (ce qui peut être compliqué dans certaines situations).

Pourquoi ne pas dissocier les actions ON, OFF et COMMUTE via trois boutons distincts comme le faisait par exemple le plug-in historique:

if ( $this->getLogicalId() == 'btn_on' )
	$url .= 'preset.htm?set'.($gceid+1).'=1';
else if ( $this->getLogicalId() == 'btn_off' )
	$url .= 'preset.htm?set'.($gceid+1).'=0';
else if ( $this->getLogicalId() == 'impulsion' )
	$url .= 'preset.htm?RLY'.($gceid+1).'=1';
else if ( $this->getLogicalId() == 'commute' )
	$url .= 'leds.cgi?led='.$gceid;

La question se pose également pour les entrées, qui disposent actuellement de boutons ON et OFF qui ont tous les deux le même effet, et pourraient donc dans cet état être remplacés par un unique bouton Commute.

**Comment by amg0** [comment]
will look at it when I back, after July 15th. thank you

**Comment by amg0** [comment]
dans la version "beta" : j'ai créer une commande commute pour commuter le relai ( impulsion ou pas depend du Ta Tb configuré dans l'IPX ). la nouvelle commande n'apparait qu'aptes une sauvegarde de l'équipement. les actions ON et le OFF sont donc maintenant des actions forcés a 1 ou 0.
